version: "3.7"

services:

  prisma:
    ports:
      - '4466:4466'

  mysql:
    ports:
      - '3306:3306'

  # front:
  #   volumes:
  #     - ./prisma-cms/${SITE:-boilerplate}/src:/www/${SITE:-boilerplate}/src
  #   command: bash -c "yarn deploy && yarn start"

  pivkarta.ru-2:
    volumes:
      - ./prisma-cms/pivkarta.ru-2/.storybook:/www/pivkarta.ru-2/.storybook
      - ./prisma-cms/pivkarta.ru-2/cypress:/www/pivkarta.ru-2/cypress
      - ./prisma-cms/pivkarta.ru-2/e2e:/www/pivkarta.ru-2/e2e
      - ./prisma-cms/pivkarta.ru-2/pages:/www/pivkarta.ru-2/pages
      - ./prisma-cms/pivkarta.ru-2/src:/www/pivkarta.ru-2/src
      - ./prisma-cms/pivkarta.ru-2/public:/www/pivkarta.ru-2/public
      - ./prisma-cms/pivkarta.ru-2/stories:/www/pivkarta.ru-2/stories
      - ./prisma-cms/pivkarta.ru-2/server:/www/pivkarta.ru-2/server
      - ./prisma-cms/pivkarta.ru-2/package.json:/www/pivkarta.ru-2/package.json
    command: bash -c "yarn dev"
    ports:
      - '3100:3000'

  api:
    volumes:
      - ./prisma-cms/${SITE:-boilerplate}/src:/www/${SITE:-boilerplate}/src
    environment: 
      - SendmailTest=true
    command: bash -c "yarn deploy && yarn start-server-dev"

  proxy:
    ports:
      - 2015:2015
      - 2016:2016
      - 2017:2017

  pma:
    ports:
      - 8090:80

  mail:
    ports:
      - 8025:8025
